# ===========================================
# GESTION SERVICE CONFIGURATION
# ===========================================
spring.application.name=gestion-service
server.port=8081

# Database
spring.datasource.url=jdbc:mysql://mysql:3306/microsUsuario?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=mysql123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# MAIL CONFIG
# ===========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=byfelipelazaro@gmail.com
spring.mail.password=bjqwnsmykzdlasjj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Eureka
eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka/
eureka.instance.prefer-ip-address=true

# ===========================================
# JWT CONFIG
# ===========================================
jwt.secret=f0d9f92e-481f
